Repository HazyResearch/fonduer, pull requests merged in 2018-05, with the labels that each got.

#50 Remove encode in __repr__ and test unicode
  CHANGELOG.rst
  fonduer/_version.py
  fonduer/lf_helpers.py
  fonduer/matchers.py
  fonduer/models/context.py
  fonduer/parser/spacy_parser.py
  tests/data/html_simple/md.html
  tests/data/pdf_simple/md.pdf
  tests/parser/test_parser.py
Labels: enhancement

#53 fix simpletokenizer
  fonduer/parser/parser.py
  tests/parser/test_parser.py
Labels: bug

#52 Extending styles parsing and RegEx search
  fonduer/matchers.py
  fonduer/parser/parser.py
  tests/data/html_extended/ext_diseases.html
  tests/data/pdf_extended/ext_diseases.pdf
  tests/parser/test_parser.py
Labels: enhancement

#55 remove viewer
  CHANGELOG.rst
  docs/conf.py
  fonduer/lf_helpers.py
  fonduer/models/annotation.py
  fonduer/viewer.py
  setup.py
Labels: clean-up
