Repository HazyResearch/fonduer, pull requests merged in 2018-11, with the labels that each got.

#174 Update CHANGELOG for hotfix
  CHANGELOG.rst
  src/fonduer/_version.py
Labels: docs

#183 Invalid rowspans
  src/fonduer/parser/parser.py
Labels: bug

#182 Improve data model
  CHANGELOG.rst
  src/fonduer/_version.py
  src/fonduer/parser/models/caption.py
  src/fonduer/parser/models/figure.py
  src/fonduer/parser/models/paragraph.py
  src/fonduer/parser/models/section.py
  src/fonduer/parser/models/sentence.py
  src/fonduer/parser/models/table.py
  src/fonduer/parser/models/webpage.py
  src/fonduer/parser/parser.py
  tests/data/pure_html/radiology.html
  tests/parser/test_parser.py
Labels: enhancement
