Repository HazyResearch/fonduer, pull requests merged in 2018-08, with the labels that each got.

#95 Fix visualizer to support new Candidate/Mention structure
  fonduer/candidates/candidates.py
  fonduer/candidates/mentions.py
  fonduer/utils/visualizer.py
  tests/shared/hardware_utils.py
Labels: bug, clean-up

#96 Only apply split at the candidate level
  fonduer/candidates/mentions.py
  fonduer/candidates/models/mention.py
  tests/candidates/test_candidates.py
  tests/e2e/test_e2e.py
Labels: clean-up

#97 Consolidate annotation code and rename BatchAnnotators
  CHANGELOG.rst
  Makefile
  fonduer/__init__.py
  fonduer/meta.py
  fonduer/supervision/__init__.py
  fonduer/supervision/annotations.py
  fonduer/supervision/async_annotations.py
  tests/candidates/test_candidates.py
  tests/e2e/test_e2e.py
Labels: clean-up

#98 Update dev docs, remove udf reducer, add default encoding to meta.py
  CHANGELOG.rst
  docs/dev/codestyle.rst
  docs/dev/install.rst
  fonduer/meta.py
  fonduer/utils/udf.py
Labels: clean-up, docs

#99 Add flake8 to pre-commit hooks
  .pre-commit-config.yaml
  Makefile
  setup.cfg
Labels: clean-up

#103 Fix pdf path validation in Parser
  CHANGELOG.rst
  docs/user/getting_started.rst
  fonduer/parser/parser.py
  fonduer/parser/visual_linker.py
  fonduer/supervision/annotations.py
  fonduer/utils/udf.py
  tests/parser/test_parser.py
  tests/shared/hardware_utils.py
Labels: bug

#105 Split annotations into utils/features/supervision
  CHANGELOG.rst
  docs/dev/codestyle.rst
  docs/dev/install.rst
  docs/index.rst
  docs/user/data_model_utils.rst
  docs/user/faqs.rst
  docs/user/getting_started.rst
  fonduer/__init__.py
  fonduer/features/__init__.py
  fonduer/features/feature_annotator.py
  fonduer/learning/classifier.py
  fonduer/parser/visual_linker.py
  fonduer/supervision/__init__.py
  fonduer/supervision/label_annotator.py
  fonduer/utils/annotations.py
Labels: clean-up

#106 move test data to server
  tests/data/digikey_part_dictionary.csv
  tests/data/hardware_tutorial_gold.csv
  tests/data/html_extended/ext_diseases.html
  tests/data/html_simple/diseases.html
  tests/data/html_simple/md.html
  tests/data/html_simple/md_para.html
  tests/data/parts_by_doc_dict.pkl
  tests/data/pdf_extended/ext_diseases.pdf
  tests/data/pdf_simple/diseases.pdf
  tests/data/pdf_simple/md.pdf
  tests/data/pdf_simple/md_para.pdf
  tests/download_data.sh
Labels: clean-up

#112 Skip TemporarySpan if it is an empty string
  fonduer/candidates/mentions.py
  tests/candidates/test_candidates.py
Labels: bug

#110 Change import syntax to be more explicit
  .isort.cfg
  CHANGELOG.rst
  MANIFEST.in
  docs/conf.py
  docs/index.rst
  docs/user/candidates.rst
  docs/user/data_model.rst
  docs/user/features.rst
  docs/user/getting_started.rst
  docs/user/learning.rst
  docs/user/matchers.rst
  docs/user/parser.rst
  docs/user/preprocessors.rst
  docs/user/supervision.rst
  fonduer/__init__.py
  fonduer/candidates/__init__.py
  fonduer/candidates/candidates.py
  fonduer/candidates/mentions.py
  fonduer/candidates/models/candidate.py
  fonduer/candidates/models/mention.py
  fonduer/features/config.py
  fonduer/features/content_features.py
  fonduer/features/feature_annotator.py
  fonduer/features/settings.json
  fonduer/features/table_features.py
  fonduer/learning/__init__.py
  fonduer/learning/classifier.py
  fonduer/learning/utils.py
  fonduer/supervision/label_annotator.py
  fonduer/supervision/models/__init__.py
  fonduer/supervision/models/annotation.py
  fonduer/utils/__init__.py
  fonduer/utils/annotations.py
  fonduer/utils/annotator.py
  fonduer/utils/data_model_utils/tabular.py
  fonduer/utils/data_model_utils/textual.py
  fonduer/utils/data_model_utils/visual.py
  fonduer/utils/utils_annotations.py
  setup.py
  tests/candidates/test_candidates.py
  tests/e2e/test_e2e.py
  tests/features/.fonduer-config.yaml
  tests/features/test_features.py
  tests/shared/hardware_matchers.py
Labels: clean-up

#113 Remove lxml version pinning and move config to utils
  docs/user/features.rst
  fonduer/features/content_features.py
  fonduer/features/table_features.py
  fonduer/parser/parser.py
  fonduer/utils/config.py
  setup.py
  tests/utils/.fonduer-config.yaml
  tests/utils/test_config.py
Labels: clean-up

#114 Reorganize supervision, learning, and util models
  fonduer/features/models/__init__.py
  fonduer/features/models/feature.py
  fonduer/learning/models/__init__.py
  fonduer/learning/models/prediction.py
  fonduer/learning/utils.py
  fonduer/meta.py
  fonduer/supervision/models/__init__.py
  fonduer/supervision/models/label.py
  fonduer/utils/config.py
  fonduer/utils/models/__init__.py
  fonduer/utils/models/annotation.py
Labels: clean-up

#118 Check if poppler-utils is installed AND the version is 0.36.0+
  fonduer/parser/visual_linker.py
Labels: enhancement

#119 Switch numbskull to MeTaL
  .isort.cfg
  .travis.yml
  CHANGELOG.rst
  docs/conf.py
  fonduer/learning/__init__.py
  fonduer/learning/disc_learning.py
  fonduer/learning/gen_learning.py
  fonduer/learning/utils.py
  setup.py
  tests/e2e/test_e2e.py
  tests/shared/hardware_lfs.py
Labels: clean-up, enhancement

#117 Parse efficiency
  CHANGELOG.rst
  fonduer/parser/parser.py
  fonduer/parser/spacy_parser.py
  fonduer/utils/udf.py
  tests/candidates/test_candidates.py
  tests/e2e/test_e2e.py
  tests/parser/test_parser.py
Labels: enhancement

#123 Introduce mocks to the tests and decouple test_parser from db
  tests/parser/test_parser.py
Labels: clean-up

#126 Add sparse LR support and reorg disc model dir
  CHANGELOG.rst
  src/fonduer/learning/__init__.py
  src/fonduer/learning/disc_learning.py
  src/fonduer/learning/disc_models/layers/rnn.py
  src/fonduer/learning/disc_models/layers/sparse_linear.py
  src/fonduer/learning/disc_models/logistic_regression.py
  src/fonduer/learning/disc_models/lstm.py
  src/fonduer/learning/disc_models/rnn/__init__.py
  src/fonduer/learning/disc_models/rnn/config.py
  src/fonduer/learning/disc_models/sparse_logistic_regression.py
  src/fonduer/learning/disc_models/utils.py
  tests/e2e/test_e2e.py
Labels: clean-up, enhancement

#131 clean torchvision dependency
  docs/conf.py
  setup.py
Labels: clean-up
