Repository HazyResearch/fonduer, pull requests merged in 2018-12, with the labels that each got.

#189 Add soft version pinning to dependencies
  CHANGELOG.rst
  setup.py
  src/fonduer/_version.py
Labels: clean-up

#192 Added alpha spacy support for Chinese tokenizer
  CHANGELOG.rst
  Makefile
  docs/user/faqs.rst
  setup.py
  src/fonduer/parser/spacy_parser.py
  tests/data/pure_html/chinese.html
  tests/parser/test_parser.py
Labels: enhancement

#194 Modified get_row_ngrams and get_col_ngrams to return None for non-table mentions
  CHANGELOG.rst
  src/fonduer/utils/data_model_utils/tabular.py
  tests/candidates/test_candidates.py
Labels: bug

#198 Support CSV, TSV, Text input data format
  CHANGELOG.rst
  src/fonduer/_version.py
  src/fonduer/parser/preprocessors/__init__.py
  src/fonduer/parser/preprocessors/csv_doc_preprocessor.py
  src/fonduer/parser/preprocessors/csv_paths_preprocessor.py
  src/fonduer/parser/preprocessors/doc_preprocessor.py
  src/fonduer/parser/preprocessors/text_doc_preprocessor.py
  src/fonduer/parser/preprocessors/tsv_doc_preprocessor.py
  src/fonduer/utils/udf.py
  src/fonduer/utils/utils_parser.py
  tests/data/various_format/csv_format.csv
  tests/data/various_format/text_format.txt
  tests/data/various_format/tsv_format.tsv
  tests/parser/test_parser.py
Labels: enhancement

#199 fix parser with multi-doc per file
  src/fonduer/candidates/models/caption_mention.py
  src/fonduer/candidates/models/cell_mention.py
  src/fonduer/candidates/models/document_mention.py
  src/fonduer/candidates/models/figure_mention.py
  src/fonduer/candidates/models/paragraph_mention.py
  src/fonduer/candidates/models/section_mention.py
  src/fonduer/candidates/models/table_mention.py
  src/fonduer/candidates/models/temporary_context.py
  src/fonduer/parser/preprocessors/csv_doc_preprocessor.py
  src/fonduer/parser/preprocessors/tsv_doc_preprocessor.py
  tests/data/various_format/csv_format.csv
  tests/data/various_format/tsv_format.tsv
  tests/parser/test_parser.py
Labels: bug

#204 Fix installation instructions
  docs/user/getting_started.rst
Labels: docs
