Repository HazyResearch/fonduer, pull requests merged in 2018-09, with the labels that each got.

#133 Streaming input
  src/fonduer/parser/preprocessors/doc_preprocessor.py
  src/fonduer/parser/preprocessors/html_doc_preprocessor.py
  src/fonduer/utils/udf.py
Labels: enhancement

#130 Multi language
  .travis.yml
  CHANGELOG.rst
  Makefile
  docs/user/faqs.rst
  setup.py
  src/fonduer/parser/parser.py
  src/fonduer/parser/spacy_parser.py
  tests/data/pure_html/brot.html
  tests/data/pure_html/japan.html
  tests/parser/test_parser.py
Labels: enhancement

#127 Refactor featurizer and labeler to use sqlalchemy bulk inserts and support multiple relations
  .gitignore
  CHANGELOG.rst
  README.rst
  setup.cfg
  setup.py
  src/fonduer/candidates/candidates.py
  src/fonduer/candidates/mentions.py
  src/fonduer/features/__init__.py
  src/fonduer/features/feature_annotator.py
  src/fonduer/features/feature_libs/__init__.py
  src/fonduer/features/feature_libs/content_features.py
  src/fonduer/features/feature_libs/core_features.py
  src/fonduer/features/feature_libs/structural_features.py
  src/fonduer/features/feature_libs/table_features.py
  src/fonduer/features/feature_libs/tree_structs.py
  src/fonduer/features/feature_libs/visual_features.py
  src/fonduer/features/features.py
  src/fonduer/features/featurizer.py
  src/fonduer/features/models/feature.py
  src/fonduer/learning/disc_models/logistic_regression.py
  src/fonduer/learning/disc_models/lstm.py
  src/fonduer/learning/disc_models/sparse_logistic_regression.py
  src/fonduer/learning/utils.py
  src/fonduer/meta.py
  src/fonduer/parser/parser.py
  src/fonduer/supervision/__init__.py
  src/fonduer/supervision/label_annotator.py
  src/fonduer/supervision/labeler.py
  src/fonduer/supervision/models/label.py
  src/fonduer/utils/annotator.py
  src/fonduer/utils/models/annotation.py
  src/fonduer/utils/udf.py
  src/fonduer/utils/utils.py
  src/fonduer/utils/utils_annotations.py
  src/fonduer/utils/utils_udf.py
  tests/candidates/test_candidates.py
  tests/e2e/test_e2e.py
  tests/parser/test_parser.py
  tests/pytest.ini
  tests/shared/hardware_utils.py
Labels: clean-up, enhancement

#135 Fix parallelism bug
  src/fonduer/utils/udf.py
Labels: bug

#138 Hotfix
  setup.py
  tests/parser/test_parser.py
Labels: bug

#136 Updating progress bar parallel
  src/fonduer/parser/preprocessors/doc_preprocessor.py
  src/fonduer/utils/udf.py
Labels: bug, enhancement

#143 update metal version to avoid symmetry-breaking issues
  setup.py
Labels: bug

#146 rename gen_learning to label_learner and move to supervision
  CHANGELOG.rst
  src/fonduer/learning/__init__.py
  src/fonduer/supervision/__init__.py
  src/fonduer/supervision/label_learner.py
  tests/e2e/test_e2e.py
Labels: clean-up

#145 Added n_min argument to the ngram class
  CHANGELOG.rst
  src/fonduer/candidates/mentions.py
  tests/candidates/test_candidates.py
  tests/data/pure_html/lincoln_short.html
Labels: enhancement

#148 Update path used in readthedocs
  docs/conf.py
Labels: bug, docs

#152 Stripped doc text and span caching hotfix
  CHANGELOG.rst
  src/fonduer/features/feature_libs/__init__.py
  src/fonduer/features/feature_libs/structural_features.py
  src/fonduer/parser/parser.py
  src/fonduer/parser/preprocessors/html_doc_preprocessor.py
  src/fonduer/utils/data_model_utils/structural.py
Labels: enhancement

#153 add docstring for learning
  docs/user/learning.rst
  src/fonduer/learning/classifier.py
  src/fonduer/learning/disc_learning.py
  src/fonduer/learning/disc_models/layers/rnn.py
  src/fonduer/learning/disc_models/layers/sparse_linear.py
  src/fonduer/learning/disc_models/logistic_regression.py
  src/fonduer/learning/disc_models/lstm.py
  src/fonduer/learning/disc_models/sparse_logistic_regression.py
  src/fonduer/learning/disc_models/utils.py
  src/fonduer/learning/utils.py
  src/fonduer/utils/config.py
Labels: docs

#154 Add supporting functions for incrementally adding docs
  CHANGELOG.rst
  src/fonduer/features/featurizer.py
  src/fonduer/parser/parser.py
  src/fonduer/utils/udf.py
  tests/e2e/test_e2e.py
  tests/parser/test_parser.py
Labels: enhancement

#155 Remove wrappers for metal functions
  CHANGELOG.rst
  README.rst
  docs/conf.py
  docs/index.rst
  docs/static/img/fonduer.svg
  src/fonduer/supervision/__init__.py
  src/fonduer/supervision/label_learner.py
  tests/e2e/test_e2e.py
Labels: clean-up, docs

#156 fix test
  tests/shared/hardware_utils.py
Labels: bug

#157 Fix MentionFigures AttributeError
  CHANGELOG.rst
  src/fonduer/_version.py
  src/fonduer/candidates/mentions.py
  src/fonduer/candidates/models/image.py
  src/fonduer/candidates/models/implicitspan.py
  src/fonduer/candidates/models/span.py
  src/fonduer/candidates/models/temporarycontext.py
  tests/candidates/test_candidates.py
Labels: bug

#158 Skip documents if parse errors occur
  CHANGELOG.rst
  src/fonduer/parser/parser.py
  src/fonduer/parser/preprocessors/doc_preprocessor.py
  src/fonduer/parser/preprocessors/html_doc_preprocessor.py
  tests/data/html_faulty/ext_diseases_missing_table_tag.html
  tests/parser/test_parser.py
Labels: enhancement

#160 Change split_token behavior and default
  CHANGELOG.rst
  src/fonduer/candidates/mentions.py
  tests/candidates/test_candidates.py
  tests/e2e/test_e2e.py
  tests/shared/hardware_spaces.py
Labels: enhancement

#164 Fix bug in get_between_ngrams
  CHANGELOG.rst
  src/fonduer/utils/data_model_utils/textual.py
Labels: bug

#165 Set longest_match_only to False by default for LambdaFunctionMatcher
  CHANGELOG.rst
  src/fonduer/candidates/matchers.py
  tests/candidates/test_candidates.py
Labels: bug
