Repository HazyResearch/fonduer, pull requests merged in 2018-07, with the labels that each got.

#60 Split sqlalchemy models into individual files
  CHANGELOG.rst
  fonduer/_version.py
  fonduer/candidates/candidates.py
  fonduer/candidates/models/__init__.py
  fonduer/candidates/models/candidate.py
  fonduer/candidates/models/image.py
  fonduer/candidates/models/implicitspan.py
  fonduer/candidates/models/span.py
  fonduer/features/content_features.py
  fonduer/features/core_features.py
  fonduer/features/structural_features.py
  fonduer/features/table_features.py
  fonduer/features/visual_features.py
  fonduer/learning/models/__init__.py
  fonduer/learning/models/marginal.py
  fonduer/parser/models/__init__.py
  fonduer/parser/models/context.py
  fonduer/parser/models/document.py
  fonduer/parser/models/figure.py
  fonduer/parser/models/phrase.py
  fonduer/parser/models/table.py
  fonduer/parser/models/webpage.py
  fonduer/supervision/annotations.py
  fonduer/supervision/lf_helpers.py
  fonduer/utils/utils_visual.py
  tests/e2e/hardware_spaces.py
Labels: clean-up

#61 Add Fonduer logo
  README.rst
  docs/dev/codestyle.rst
  docs/index.rst
  docs/static/img/fonduer-logo.png
Labels: docs, enhancement

#64 Split doc_preprocessors into separate files
  .travis.yml
  CHANGELOG.rst
  Makefile
  fonduer/__init__.py
  fonduer/parser/__init__.py
  fonduer/parser/doc_preprocessors.py
  fonduer/parser/models/context.py
  fonduer/parser/models/table.py
  fonduer/parser/parser.py
  fonduer/parser/preprocessors/__init__.py
  fonduer/parser/preprocessors/csv_paths_preprocessor.py
  fonduer/parser/preprocessors/doc_preprocessor.py
  fonduer/parser/preprocessors/html_doc_preprocessor.py
  fonduer/parser/preprocessors/text_doc_preprocessor.py
  fonduer/parser/preprocessors/tsv_doc_preprocessor.py
  fonduer/parser/preprocessors/xml_multidoc_preprocessor.py
  fonduer/parser/rule_parser.py
  fonduer/parser/spacy_parser.py
  requirements-dev.txt
  tests/e2e/test_e2e.py
  tests/parser/test_parser.py
Labels: clean-up

#70 Minor parser clean-up
  fonduer/candidates/models/__init__.py
  fonduer/candidates/models/image.py
  fonduer/candidates/models/span.py
  fonduer/candidates/models/temporarycontext.py
  fonduer/parser/models/context.py
  fonduer/parser/models/phrase.py
  fonduer/parser/parser.py
  fonduer/parser/simple_tokenizer.py
  fonduer/parser/visual_linker.py
  tests/parser/test_parser.py
Labels: clean-up

#72 Switch from Phrase to Sentence
  fonduer/__init__.py
  fonduer/candidates/candidates.py
  fonduer/candidates/matchers.py
  fonduer/features/table_features.py
  fonduer/parser/models/__init__.py
  fonduer/parser/models/sentence.py
  fonduer/parser/parser.py
  fonduer/parser/simple_tokenizer.py
  fonduer/parser/visual_linker.py
  fonduer/supervision/lf_helpers.py
  fonduer/utils/utils_visual.py
  fonduer/utils/visualizer.py
  tests/e2e/hardware_spaces.py
  tests/e2e/test_e2e.py
  tests/parser/test_parser.py
Labels: clean-up

#74 Simplify parsing code
  Makefile
  fonduer/__init__.py
  fonduer/parser/__init__.py
  fonduer/parser/parser.py
  fonduer/parser/preprocessors/doc_preprocessor.py
  tests/e2e/test_e2e.py
  tests/parser/test_parser.py
Labels: clean-up

#76 Add Paragraph and Section Contexts
  Makefile
  fonduer/parser/models/figure.py
  fonduer/parser/models/paragraph.py
  fonduer/parser/models/section.py
  fonduer/parser/models/sentence.py
  fonduer/parser/models/table.py
  fonduer/parser/parser.py
  tests/data/html_simple/md_para.html
  tests/data/pdf_simple/md_para.pdf
  tests/parser/test_parser.py
Labels: enhancement

#78 Add basic figure and figcaption support
  fonduer/parser/parser.py
  tests/data/html_simple/md_para.html
  tests/data/pdf_simple/md_para.pdf
  tests/e2e/test_e2e.py
  tests/parser/test_parser.py
Labels: enhancement

#81 reorg_lf_helpers
  fonduer/features/content_features.py
  fonduer/supervision/lf_helpers.py
  fonduer/supervision/lf_helpers/__init__.py
  fonduer/supervision/lf_helpers/structural.py
  fonduer/supervision/lf_helpers/tabular.py
  fonduer/supervision/lf_helpers/textual.py
  fonduer/supervision/lf_helpers/visual.py
  tests/e2e/test_e2e.py
Labels: clean-up

#84 Support Figures inside Cells and Paragraphs in Figure
  CHANGELOG.rst
  fonduer/_version.py
  fonduer/parser/models/figure.py
  fonduer/parser/parser.py
  tests/data/html_simple/md_para.html
  tests/data/pdf_simple/md_para.pdf
  tests/parser/test_parser.py
Labels: enhancement

#85 Split up lf_helpers by modality in docs
  CHANGELOG.rst
  docs/user/lf_helpers.rst
  fonduer/_version.py
  fonduer/supervision/lf_helpers/__init__.py
  fonduer/supervision/lf_helpers/utils.py
Labels: clean-up, docs

#87 Remove get parent/children/sentence generator from Context
  CHANGELOG.rst
  fonduer/_version.py
  fonduer/candidates/models/span.py
  fonduer/parser/models/context.py
  fonduer/parser/models/document.py
Labels: clean-up

#88 Only clear candidates associated with a CandidateExtractor
  fonduer/candidates/candidates.py
  fonduer/candidates/models/candidate.py
Labels: enhancement
