Repository HazyResearch/fonduer, pull requests merged in 2019-01, with the labels that each got.

#203 Reorganize learning module
  .isort.cfg
  .readthedocs.yml
  .travis.yml
  CHANGELOG.rst
  docs/conf.py
  docs/dev/tests.rst
  src/fonduer/candidates/mentions.py
  src/fonduer/learning/classifier.py
  src/fonduer/learning/disc_learning.py
  src/fonduer/learning/disc_models/logistic_regression.py
  src/fonduer/learning/disc_models/lstm.py
  src/fonduer/learning/disc_models/modules/__init__.py
  src/fonduer/learning/disc_models/modules/loss.py
  src/fonduer/learning/disc_models/modules/rnn.py
  src/fonduer/learning/disc_models/modules/sparse_linear.py
  src/fonduer/learning/disc_models/sparse_logistic_regression.py
  src/fonduer/learning/disc_models/sparse_lstm.py
  src/fonduer/learning/disc_models/utils.py
  src/fonduer/learning/utils.py
  tests/candidates/test_candidates.py
  tests/e2e/test_e2e.py
  tests/e2e/test_incremental.py
  tests/shared/hardware_spaces.py
Labels: clean-up

#207 fix max/min in visualizer.get_box
  CHANGELOG.rst
  src/fonduer/utils/visualizer.py
Labels: bug

#209 update to pytorch 1.0
  .travis.yml
  setup.py
Labels: enhancement
