Repository HazyResearch/fonduer, pull requests merged in 2020-04, with the labels that each got.

#395 switch to codecov
  .codecov.yaml
  .coveragerc
  .github/workflows/pythonpackage.yml
  README.rst
Labels: enhancement

#398 Support MTL for LSTM and LogisticRegression
  CHANGELOG.rst
  docs/user/config.rst
  docs/user/learning.rst
  src/fonduer/learning/modules/concat_linear.py
  src/fonduer/learning/modules/sum_module.py
  src/fonduer/learning/task.py
  src/fonduer/utils/config.py
  tests/e2e/test_e2e.py
Labels: enhancement

#405 Add table parameter to docstring (fix #402)
  src/fonduer/supervision/labeler.py
Labels: docs

#408 Fix a typing
  src/fonduer/supervision/labeler.py
Labels: clean-up

#409 refactor(supervision/labeler): raise error if gold contains ABSTAIN
  src/fonduer/supervision/labeler.py
  tests/e2e/test_e2e.py
Labels: enhancement

#411 build(pre-commit): update to latest versions of pre-commit hooks
  .pre-commit-config.yaml
Labels: clean-up
