Repository HazyResearch/fonduer, pull requests merged in 2020-05, with the labels that each got.

#416 Improve documentation of preprocessors
  docs/conf.py
  src/fonduer/parser/preprocessors/csv_doc_preprocessor.py
  src/fonduer/parser/preprocessors/doc_preprocessor.py
  src/fonduer/parser/preprocessors/html_doc_preprocessor.py
  src/fonduer/parser/preprocessors/text_doc_preprocessor.py
  src/fonduer/parser/preprocessors/tsv_doc_preprocessor.py
Labels: clean-up

#421 Enabled "Type hints (PEP 484) support for the Sphinx autodoc extension"
  CHANGELOG.rst
  docs/conf.py
  requirements-dev.txt
Labels: docs

#420 Fix minimum range difference for cols/rows in case of negative numbers
  CHANGELOG.rst
  src/fonduer/utils/utils_table.py
  tests/utils/test_utils_table.py
Labels: bug

#427 Remove ":type" and ":rtype" from the docstring when they are redundant
  src/fonduer/candidates/candidates.py
  src/fonduer/candidates/matchers.py
  src/fonduer/candidates/mentions.py
  src/fonduer/candidates/models/candidate.py
  src/fonduer/candidates/models/caption_mention.py
  src/fonduer/candidates/models/cell_mention.py
  src/fonduer/candidates/models/document_mention.py
  src/fonduer/candidates/models/figure_mention.py
  src/fonduer/candidates/models/implicit_span_mention.py
  src/fonduer/candidates/models/paragraph_mention.py
  src/fonduer/candidates/models/section_mention.py
  src/fonduer/candidates/models/span_mention.py
  src/fonduer/candidates/models/table_mention.py
  src/fonduer/features/feature_extractors.py
  src/fonduer/features/feature_libs/structural_features.py
  src/fonduer/features/feature_libs/tabular_features.py
  src/fonduer/features/feature_libs/textual_features.py
  src/fonduer/features/feature_libs/tree_structs.py
  src/fonduer/features/feature_libs/visual_features.py
  src/fonduer/features/featurizer.py
  src/fonduer/learning/dataset.py
  src/fonduer/learning/modules/concat_linear.py
  src/fonduer/learning/modules/soft_cross_entropy_loss.py
  src/fonduer/learning/task.py
  src/fonduer/learning/utils.py
  src/fonduer/meta.py
  src/fonduer/parser/lingual_parser/lingual_parser.py
  src/fonduer/parser/lingual_parser/simple_parser.py
  src/fonduer/parser/lingual_parser/spacy_parser.py
  src/fonduer/parser/models/sentence.py
  src/fonduer/parser/models/utils.py
  src/fonduer/parser/parser.py
  src/fonduer/parser/preprocessors/csv_doc_preprocessor.py
  src/fonduer/parser/preprocessors/doc_preprocessor.py
  src/fonduer/parser/preprocessors/tsv_doc_preprocessor.py
  src/fonduer/parser/visual_linker.py
  src/fonduer/supervision/labeler.py
  src/fonduer/utils/data_model_utils/structural.py
  src/fonduer/utils/data_model_utils/tabular.py
  src/fonduer/utils/data_model_utils/textual.py
  src/fonduer/utils/data_model_utils/utils.py
  src/fonduer/utils/data_model_utils/visual.py
  src/fonduer/utils/udf.py
  src/fonduer/utils/utils_parser.py
  src/fonduer/utils/utils_udf.py
  src/fonduer/utils/visualizer.py
Labels: clean-up
